language: node_js
node_js:
  - "5.5.0"
addons:
  code_climate:
    repo_token: 4a414e5fec30cbdab00f81e9a14e2ce3dd927770223a11b662916f4d1bf7dea2
script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
